apiVersion: v1
kind: Service
metadata:
  name: mydjangoapp1
  namespace: myapp2
spec:
  type: ClusterIP
  selector:
    app: mydjangoapp1 #internal only.
  ports:
    - port: 8091
      targetPort: 8000
